-- ─── Drivers table (MySQL – source of truth) ─────────────
-- UUID primary key generated by the NestJS service before Kafka publish.
-- Debezium CDC will replicate changes to the cache database.

USE core_business;

CREATE TABLE IF NOT EXISTS drivers (
    id              CHAR(36)     NOT NULL PRIMARY KEY,
    tenant_id       VARCHAR(50)  NOT NULL,
    name            VARCHAR(200) NOT NULL,
    device_id       VARCHAR(100),
    phone           VARCHAR(50),
    vehicle_plate   VARCHAR(50),
    vehicle_type    VARCHAR(50)  NOT NULL DEFAULT 'van',
    status          VARCHAR(50)  NOT NULL DEFAULT 'offline',
    created_at      DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at      DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    INDEX idx_drivers_tenant (tenant_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
