import { Entity, Column, PrimaryColumn, Index } from 'typeorm';

/**
 * MySQL `core_business.drivers` — source of truth.
 *
 * Mirrors `infrastructure/mysql/init/03-drivers.sql`. `id` is a CHAR(36) UUID
 * generated by the tracking-service *before* the Kafka command is published, so
 * it is a plain primary column (not generated here). `vehicle_type`, `status`,
 * `created_at`, `updated_at` fall back to MySQL defaults when not provided.
 */
@Entity('drivers')
export class DriverEntity {
  @PrimaryColumn({ type: 'char', length: 36 })
  id!: string;

  @Index('idx_drivers_tenant')
  @Column({ name: 'tenant_id', type: 'varchar', length: 50 })
  tenantId!: string;

  @Column({ type: 'varchar', length: 200 })
  name!: string;

  @Column({ name: 'device_id', type: 'varchar', length: 100, nullable: true })
  deviceId!: string | null;

  @Column({ type: 'varchar', length: 50, nullable: true })
  phone!: string | null;

  @Column({ name: 'vehicle_plate', type: 'varchar', length: 50, nullable: true })
  vehiclePlate!: string | null;

  @Column({ name: 'vehicle_type', type: 'varchar', length: 50, default: 'van' })
  vehicleType!: string;

  @Column({ type: 'varchar', length: 50, default: 'offline' })
  status!: string;
}
